version: '3.8'

services:
  lara:
    build:
      context: ./docker/php
    container_name: lara
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - lara-network
    environment:
      - DB_HOST=postgres
      - DB_DATABASE=laravel
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret

  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    ports:
      - "8085:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lara
    networks:
      - lara-network

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - lara-network

volumes:
  postgres-data:

networks:
  lara-network:
    driver: bridge
